##
## EPITECH PROJECT, 2020
## MAKE FILE
## File description:
## NO DESCRIPTION
##

SRC = main.c

NAME = do-op

$(NAME):
	gcc -o $(NAME) $(SRC) -lmy -L../lib/

all: $(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all
